---
title: "psyTeachR Google Analytics"
output: 
  html_document:
    df_print: paged
    theme: 
      version: 4
      bootswatch: cosmo
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  warning = FALSE,
  message = FALSE,
  out.width = "100%"
)
library(tidyverse)
library(patchwork)
library(DT)
theme_set(theme_minimal())
Sys.setenv("VROOM_CONNECTION_SIZE" = 200000)
```



```{r}
# import data

# !Remember to set Search to "Page path + query string and screen" 
# and add "Hostname" before downloading data

# files are structured poorly, so search for the full header 

headers <- "Page path + query string and screen class,Hostname,Views,Users,New users,Views per user,Average engagement time,Unique user scrolls,Event count,Conversions,Total revenue"

files <- list.files("data", full.names = TRUE)

datalist <- list()

for (file in files) {
  #cat(file, "\n")
  lines <- readLines(file)
  skip <- grepl(headers, lines, fixed = TRUE) %>% which() - 1
  
  lines[grepl("Page path", lines, fixed = TRUE) %>% which()]
  
  start_date <- gsub("# Start date: ", "", lines[8], fixed = TRUE) %>%
    lubridate::as_date()
  end_date <- gsub("# End date: ", "", lines[9], fixed = TRUE) %>%
    lubridate::as_date()

  datalist[[file]] <- read_csv(file, 
                   skip = skip, 
                   show_col_types = FALSE) %>%
    mutate(start_date = start_date, end_date = end_date)
}

data <- do.call(bind_rows, datalist)

```

Data from `r min(data$start_date)` to `r max(data$end_date)`


```{r}
data2 <- data %>%
  filter(grepl("psyteachr", Hostname)) %>%
  separate(1, into = c("url", "query"), 
           sep = "\\?", 
           fill = "right") %>%
  separate(url, into = c("base", "book", "page"), 
           sep = "/", 
           fill = "right",
           extra = "merge") %>%
  select(-base) %>%
  mutate(book = ifelse(book %in% c("", "index.html"), "_psyTeachR_", book)) %>%
  filter(!is.na(book))
```


## Views by book

```{r}
data2 %>%
  group_by(book) %>%
  summarise(views = sum(Views),
            pages = n_distinct(page), 
            total_hours = sum(Views * `Average engagement time`),
            .groups = "drop") %>%
  mutate(total_hours = round(total_hours/60/60, 1)) %>%
  arrange(desc(views)) %>%
  DT::datatable()
```



```{r}
book_by_week <- data2 %>%
  group_by(book, start_date) %>%
  summarise(users = sum(Users),
            views = sum(Views),
            .groups = "drop")

book_order <- book_by_week %>%
  group_by(book) %>%
  summarise(total = sum(views),
            .groups = "drop") %>%
  arrange(book) %>%
  pull(book)

book_by_week$book <- factor(book_by_week$book, levels = book_order)
```



```{r}
# plotting function
week_plot <- function(data, col, min = 1, max = 1e5) {
  data %>%
    group_by(book) %>%
    filter(max(.data[[col]]) >= min, max(.data[[col]]) < max) %>%
    ungroup() %>%
    ggplot(aes(x = start_date, y = .data[[col]])) +
    geom_point(size = 2, color = "dodgerblue") +
    geom_line(size = 1, color = "dodgerblue3") +
    scale_x_date(name = "",
                 date_breaks = "1 week",
                 date_label = "%b-%d") +
    facet_wrap(~book, ncol = 1) +
    expand_limits(y=0) +
    theme(axis.text.x = element_text(angle = 45, hjust = 1))
}
```


## Views per week {.tabset}

```{r, results='asis'}
invisible({
  book_by_week %>% 
    dplyr::group_split(book) %>% 
    purrr::imap(., ~{
      # create tabset for each group 
      bookname <- as.character(unique(..1$book))
      cat('\n### ', bookname, '   \n\n')
      p <- week_plot(..1, "views")
      print(p)
      cat('\n')
    })
})

```


## Users per week  {.tabset}

```{r, results='asis'}
invisible({
  book_by_week %>% 
    dplyr::group_split(book) %>% 
    purrr::imap(., ~{
      # create tabset for each group 
      bookname <- as.character(unique(..1$book))
      cat('\n### ', bookname, '   \n\n')
      p <- week_plot(..1, "users")
      print(p)
      cat('\n')
    })
})

```



